# Generated by Django 3.2.5 on 2021-07-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweeted_at',
            field=models.DateTimeField(null=True, verbose_name='ツイート予定日時'),
        ),
    ]
